### ISSUE TITLE
Crash when generating using a structure NBT file

### ISSUE THREAD

**Issue by mounderfod** [DeadlyMC/ProtoSky#5]
Crash log: [https://paste.ee/p/XapXy](https://paste.ee/p/XapXy)
Datapack used: [Soaring Sky Data.zip](https://github.com/DeadlyMC/ProtoSky/files/5075229/Soaring.Sky.Data.zip)

When trying to use a custom structure .nbt file to place down an island when generating a world, the game completely crashes upon first load and upon any further attempts to load the world. There are numerous errors along the lines of `We are asking a region for a chunk out of bound`, followed by either a chunk or region coordinate which is different depending on the structure I use. I've tried with various different structures, attached is the latest one.

**Comment by dododome01** [comment]
It looks like the position for the Spawn island is the chunkpos multiplied by 8, instead of 16, resulting in the island to be spawned outside of the loaded world. Im not sure if thats the problem, but changing it fixed it for the version i have.
The line that has to be changed is in WorldgenUtils at line 76.
Id fix it myself, but im quite new to git(hub) and dont know how to do shit.
